#!/usr/bin/env bash
# scripts/decisions-context.sh
#
# Extracts a compact, agent-readable summary of DECISIONS.md for use as
# prompt context during the pre-planning contradiction check.
#
# Rather than loading the full DECISIONS.md (which can be thousands of tokens),
# this script prints:
#   - Every decision heading (date + title)
#   - Each decision's "Constraints introduced" lines
#   - Optionally the full text of the N most recent decisions
#
# Usage:
#   bash scripts/decisions-context.sh
#   bash scripts/decisions-context.sh --full-recent 5      # last 5 in full
#   bash scripts/decisions-context.sh --headings-only      # headings + constraints only
#   bash scripts/decisions-context.sh --file path/to/DECISIONS.md
#
# Output is plain text, safe to paste directly into an agent prompt as context.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DECISIONS_FILE="$ROOT_DIR/DECISIONS.md"
FULL_RECENT=3
HEADINGS_ONLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --full-recent)
      FULL_RECENT="${2:-3}"
      shift 2
      ;;
    --headings-only)
      HEADINGS_ONLY=1
      shift
      ;;
    --file)
      DECISIONS_FILE="${2}"
      shift 2
      ;;
    *)
      echo "[decisions-context] unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

if [[ ! -f "$DECISIONS_FILE" ]]; then
  echo "[decisions-context] DECISIONS.md not found at: $DECISIONS_FILE" >&2
  exit 1
fi

# ── Parse decision blocks ─────────────────────────────────────────────────────
# Each decision starts with a level-2 heading: ## YYYY-MM-DD: Title

declare -a headings=()
declare -A constraints=()   # heading -> constraints text
declare -a blocks=()         # full block text per heading

current_heading=""
current_block=""
current_constraints=""

while IFS= read -r line || [[ -n "$line" ]]; do
  if [[ "$line" =~ ^##[[:space:]][0-9]{4}-[0-9]{2}-[0-9]{2}:[[:space:]] ]]; then
    # Save previous block
    if [[ -n "$current_heading" ]]; then
      headings+=("$current_heading")
      constraints["$current_heading"]="$current_constraints"
      blocks+=("$current_block")
    fi
    current_heading="${line#\#\# }"
    current_block="$line"$'\n'
    current_constraints=""
  elif [[ -n "$current_heading" ]]; then
    current_block+="$line"$'\n'
    # Capture constraint lines
    if [[ "$line" =~ ^[[:space:]]*-[[:space:]]?\*\*[Cc]onstraint || \
          "$line" =~ [Cc]onstraint ]]; then
      current_constraints+="  $line"$'\n'
    fi
  fi
done < "$DECISIONS_FILE"

# Flush final block
if [[ -n "$current_heading" ]]; then
  headings+=("$current_heading")
  constraints["$current_heading"]="$current_constraints"
  blocks+=("$current_block")
fi

total="${#headings[@]}"

if [[ "$total" -eq 0 ]]; then
  echo "[decisions-context] No decision entries found in $DECISIONS_FILE"
  exit 0
fi

# ── Output ────────────────────────────────────────────────────────────────────

echo "# DECISIONS CONTEXT (generated by decisions-context.sh)"
echo "# Source: $DECISIONS_FILE"
echo "# Total decisions: $total"
echo "# Use this as pre-planning context to check for contradictions."
echo ""

if [[ "$HEADINGS_ONLY" -eq 1 ]]; then
  echo "## Decision index (headings + constraints)"
  echo ""
  for i in "${!headings[@]}"; do
    echo "### ${headings[$i]}"
    if [[ -n "${constraints[${headings[$i]}]:-}" ]]; then
      echo "Constraints:"
      echo "${constraints[${headings[$i]}]}"
    else
      echo "  (no explicit constraint lines)"
    fi
    echo ""
  done
  exit 0
fi

# Full output: index + recent N in full
echo "## Decision index (all)"
echo ""
for i in "${!headings[@]}"; do
  echo "- ${headings[$i]}"
  if [[ -n "${constraints[${headings[$i]}]:-}" ]]; then
    echo "  Constraints: ${constraints[${headings[$i]}]}" | tr '\n' ' '
    echo ""
  fi
done
echo ""

# Recent N decisions in full
start_idx=$(( total - FULL_RECENT ))
if [[ "$start_idx" -lt 0 ]]; then start_idx=0; fi

echo "## Full text: ${FULL_RECENT} most recent decisions"
echo ""
for (( i=start_idx; i<total; i++ )); do
  echo "${blocks[$i]}"
done
